[flavor]
use = "catppuccin-mocha"

[mode]
normal_main = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
normal_alt  = { fg = "#89b4fa", bg = "#313244" }
select_main = { fg = "#1e1e2e", bg = "#94e2d5", bold = true }
select_alt  = { fg = "#94e2d5", bg = "#313244" }
unset_main  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt   = { fg = "#f2cdcd", bg = "#313244" }

[status]
overall = { bg = "#181825" }
