[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "code" },
]
